hyrcania:
  build: "."
  ports: 
    - "3000:3000"
  volumes:
    - '.:/usr/src/app'
  links:
    - mongo:mongo
  environment:
    NODE_ENV: development
    DB_ENV: compose
  command: nodemon -L app.js

webpack:
  image: 'node:9.9.0'
  ports: 
    - '8080:8080'
  volumes:
    - '.:/usr/src/app'
  environment:
    PORT: 8080
  working_dir: /usr/src/app/client
  command: npm start 

mongo:
  image: "mongo:3.0.5"
